### ISSUE TITLE
[CSG]: transformations not always accurate

### ISSUE THREAD

**Issue by martin-henz** [source-academy/modules#292]
Here is a program that should result in a Mosely snowflake:

https://share.sourceacademy.org/lab29

Here is the output.

<img width="336" alt="Screenshot 2024-03-15 at 11 01 50 AM" src="https://github.com/source-academy/modules/assets/30220768/bf4299e0-1ad1-4ecf-9b81-599b8330577f">

The red circle indicates a possible bug: a wrongly displaced component.

**Comment by Cloud7050** [comment]
While breaking down the program to see how the shapes change with each operation, I changed the unit cube to better visualise what the first iteration of the fractal looks like:

```js
const c = translate(scale(cube('#88ccff'), 0.5, 0.5, 0.5), 0.25, 0.25, 0.25);
```

This is what I saw:

![image](https://github.com/source-academy/modules/assets/44526554/115b33ec-725d-4785-ad2e-3d0c03d7f5d6)

It would appear that the 2 circled portions of the fractal are actually 3 cubes stacked next to each other, and not a single cube. Perhaps that is causing the strangeness seen in the second iteration of the fractal.

Changing `center_row` to the following appears to fix the fractal (`s` instead of `inner_row`):

```js
    const center_row = before_frac(f, 
                           s,
                           before(empty, 
                             s));
```

![image](https://github.com/source-academy/modules/assets/44526554/e67a96fa-ad68-4c90-8d93-a6230896953f)

https://share.sourceacademy.org/lww29

**Comment by martin-henz** [comment]
Yes, correct. I found the bug too. Here is the correct program:

https://share.sourceacademy.org/lww29

So sorry for the confusion!
