### ISSUE TITLE
[CURVE and RUNE]: drawing should not depend on evaluation result

### ISSUE THREAD

**Issue by martin-henz** [source-academy/modules#65]
# Feature

```
import {draw_connected_full_view, unit_circle } from "curve";
draw_connected_full_view(500)(unit_circle);
0;
```
should draw the circle. Currently the drawers only draw when the result of the evaluation is a drawing. With the separate curve window, we can eliminate this hack.

**Comment by Anonymxtrix** [comment]
This issue is related to https://github.com/source-academy/modules/issues/56.

# Proposed Solution

## Outcome

The solution aims to achieve the following outcomes.
- To allow module bundles and tabs to have access to a shared state without needing to rely on the evaluation result of the Source Program. 

In  the Source evaluation context
```typescript
export interface Context<T = any> {
  // Here lies all information related to the importing of modules
  modules: {
    // Individually, each bundle and tab will have access to the corresponding state.
    // Bundles and tabs will be able to directly read and mutate this shared state to
    // interact with each other. 
    state: {
      module_name: {
        // counter: 0
      }
    }
    tabs: any[]
  }
}
```

During the compilation process of the bundles, the bundle should be wrapped in a manner similar to [NodeJS modules](https://blog.risingstack.com/node-js-at-scale-module-system-commonjs-require/#whatisthemodulesystem). 3 main things will be passed into the wrapped bundle function as arguments, `exports`, `state` and `config`. `exports` should contain the functions to be provided by the module to Source programmers to use in Source programs. `state` should be a reference to the shared state in the evaluation `Context` in JS-Slang. `config` will be the new name for `__params` used previously. 

```typescript
function (exports, state, config) {
  // Here lies the program written in the module bundles. 
  
  // To expose a counter to the module's tab
  state.counter = config.counter.defaultValue
  
  exports.increment = func () {
    state.counter++
  }

  exports.decrement= func () {
    state.counter--
  }
}
```

The module tab should be able to access this counter through the `DebuggerContext` which should contain a reference to the state through `modules.state` in the returned `Context`

**Comment by martin-henz** [comment]
Yes, this makes sense to me.
