### ISSUE TITLE
[SOUND]: play_concurrently vs play return types

### ISSUE THREAD

**Issue by solarrabbit99** [source-academy/modules#74]
## Expected Behavior

`play()` and `play_concurrently()` should both spawn sound tab if either of which is the last statement of the program, regardless of which to store as the downloadable audio file.

## Current Behavior

`play()` returns **AudioPlayed** while `play_concurrently()` is purely a consumer. Hence, no sound tab is spawned.

## Steps to Reproduce

1. Proceed to [source academy deployment playground](https://sourceacademy.org/playground)
2. Paste the following code in:
```javascript
import {
    play,
    play_concurrently,
    noise_sound
} from "sound";

play(noise_sound(0.5));
play_concurrently(noise_sound(0.5));
```
3. Click on **Run**

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Version used: master branch
- Browser Name and version: Google Chrome (Version 91.0.4472.114)
- Operating System and version (desktop or mobile): macOS Catalina

**Comment by Cloud7050** [comment]
This bug no longer occurs with the introduction and adoption of the module state system. Programs in rune and curve no longer need to evaluate to a rune or curve at the end of the program in order to spawn the tab. They can be called throughout the program, and multiple items are supported in the tab.
